### ISSUE TITLE
the shader won't turn on

### ISSUE THREAD

**Issue by windateXd** [Merlin1809/Eclipse-Shader#160]
Shader compilation failed, see log for details

**Comment by Merlin1809** [comment]
cant help you without you giving the log...

**Comment by windateXd** [comment]
where do i find it

**Comment by Merlin1809** [comment]
Minecraft/logs/latest.log

**Comment by windateXd** [comment]
[2026-04-17-1.log.gz](https://github.com/user-attachments/files/26857697/2026-04-17-1.log.gz)
line 2877

**Comment by windateXd** [comment]
my bad for not responding quickly, i dont go on github that often

**Comment by Merlin1809** [comment]
uninstall photonics mod... it does not work with eclipse on 1.21.4, you need 1.21.11
